<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Diego Pinto">

<title>Missing Values</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="cleaning_3_missing_values_files/libs/clipboard/clipboard.min.js"></script>
<script src="cleaning_3_missing_values_files/libs/quarto-html/quarto.js"></script>
<script src="cleaning_3_missing_values_files/libs/quarto-html/popper.min.js"></script>
<script src="cleaning_3_missing_values_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cleaning_3_missing_values_files/libs/quarto-html/anchor.min.js"></script>
<link href="cleaning_3_missing_values_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cleaning_3_missing_values_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cleaning_3_missing_values_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cleaning_3_missing_values_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cleaning_3_missing_values_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#dealing-with-missing-values" id="toc-dealing-with-missing-values" class="nav-link active" data-scroll-target="#dealing-with-missing-values">Dealing with missing values</a>
  <ul class="collapse">
  <li><a href="#analyzing-missing-values" id="toc-analyzing-missing-values" class="nav-link" data-scroll-target="#analyzing-missing-values">Analyzing missing values</a>
  <ul class="collapse">
  <li><a href="#what-is-the-ratio-of-missing-values-in-the-entire-dataset" id="toc-what-is-the-ratio-of-missing-values-in-the-entire-dataset" class="nav-link" data-scroll-target="#what-is-the-ratio-of-missing-values-in-the-entire-dataset">What is the ratio of missing values in the entire dataset?</a></li>
  <li><a href="#what-section-of-the-survey-contains-the-most-missing-values" id="toc-what-section-of-the-survey-contains-the-most-missing-values" class="nav-link" data-scroll-target="#what-section-of-the-survey-contains-the-most-missing-values">What section of the survey contains the most missing values?</a></li>
  <li><a href="#what-is-the-rate-of-missing-values-per-item" id="toc-what-is-the-rate-of-missing-values-per-item" class="nav-link" data-scroll-target="#what-is-the-rate-of-missing-values-per-item">What is the rate of missing values per item?</a></li>
  <li><a href="#how-many-observations-do-not-contain-missing-values-and-how-many-do-after-removing-careless-responses" id="toc-how-many-observations-do-not-contain-missing-values-and-how-many-do-after-removing-careless-responses" class="nav-link" data-scroll-target="#how-many-observations-do-not-contain-missing-values-and-how-many-do-after-removing-careless-responses">How many observations do not contain missing values and how many do (after removing careless responses)?</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul></li>
  <li><a href="#removing-or-imputing-observations" id="toc-removing-or-imputing-observations" class="nav-link" data-scroll-target="#removing-or-imputing-observations">Removing or Imputing Observations</a>
  <ul class="collapse">
  <li><a href="#littles-1988-test-of-missingness" id="toc-littles-1988-test-of-missingness" class="nav-link" data-scroll-target="#littles-1988-test-of-missingness">Little’s (1988) Test of Missingness</a></li>
  </ul></li>
  <li><a href="#multiple-imputation-by-chained-equations" id="toc-multiple-imputation-by-chained-equations" class="nav-link" data-scroll-target="#multiple-imputation-by-chained-equations">Multiple Imputation by Chained Equations</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Missing Values</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Diego Pinto </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="dealing-with-missing-values" class="level1">
<h1>Dealing with missing values</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"~/Desktop/R_projects/msc"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># Clear Global Environment</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mice"</span>) <span class="co">#for multiple imputation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'mice'

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    cbind, rbind</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/middle_school_music_mindsets_clean_2_careless_removed.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 528 Columns: 65
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (8): school, race, hispanic_latino, gender, currentSchoolMusic, current...
dbl (57): survey_id, grade, age, s1_1, s1_2, s1_3, s1_4, s1_5, s1_6, s1_7, s...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="analyzing-missing-values" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-missing-values">Analyzing missing values</h2>
<section id="what-is-the-ratio-of-missing-values-in-the-entire-dataset" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-ratio-of-missing-values-in-the-entire-dataset">What is the ratio of missing values in the entire dataset?</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>missing_sum <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(data)) <span class="co">#sum of all missing values</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>data_points_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data) <span class="sc">*</span> <span class="fu">ncol</span>(data) <span class="co">#number of datapoints in the datafrae</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>missing_percentage <span class="ot">&lt;-</span> missing_sum <span class="sc">/</span>data_points_count <span class="co">#percentage of all missing values</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_percentage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03018648</code></pre>
</div>
</div>
<p>The dataset contained 1036 missing data points, which corresponds to 3.02% of the entire data set.</p>
</section>
<section id="what-section-of-the-survey-contains-the-most-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="what-section-of-the-survey-contains-the-most-missing-values">What section of the survey contains the most missing values?</h3>
<section id="save-section-of-survey-into-separate-dataframes-for-following-calculations" class="level4">
<h4 class="anchored" data-anchor-id="save-section-of-survey-into-separate-dataframes-for-following-calculations">Save section of survey into separate dataframes for following calculations:</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>data_demographic <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(survey_id<span class="sc">:</span>currentSchoolMusic) <span class="co">#demographic variables, except currentSchoolMusic_other</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"s1"</span>)) <span class="co">#section 1 (Likert 1-4)</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"s2"</span>)) <span class="co">#section 2 (Likert 1-7, mostly)</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"s3"</span>)) <span class="co">#section 3 (Likert 1-4)</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>measures_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(s1_1<span class="sc">:</span>s3_28) <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="co">#sections 1, 2, and 3 combined, excluding variables with character data (i.e., instrument_play_best).</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co">#data_family_subset &lt;- filter(data, is.na(data$s2_8))</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co">#survey_id &lt;- data$survey_id</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="calculate-missing-values-per-survey-section" class="level4">
<h4 class="anchored" data-anchor-id="calculate-missing-values-per-survey-section">Calculate missing values per survey section</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in demographic questions</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>demographics_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(data_demographic))) <span class="sc">/</span> (<span class="fu">nrow</span>(data_demographic) <span class="sc">*</span> <span class="fu">ncol</span>(data_demographic))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in sections 1</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>s1_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(s1))) <span class="sc">/</span> (<span class="fu">nrow</span>(s1) <span class="sc">*</span> <span class="fu">ncol</span>(s1))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in section 2 (s21_:s2)</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>s2_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(s2))) <span class="sc">/</span> (<span class="fu">nrow</span>(s2) <span class="sc">*</span> <span class="fu">ncol</span>(s2))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in sections 3</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>s3_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(s3))) <span class="sc">/</span> (<span class="fu">nrow</span>(s3) <span class="sc">*</span> <span class="fu">ncol</span>(s3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The rate of missing data per survey section was as follow:</p>
<p>• Demographics: 3.48%</p>
<p>• Section 1: 1.06%</p>
<p>• Section 2: 0.88%</p>
<p>• Section 3: 1.75%</p>
<p>The demographic section has highest rate of missing values. Still, that rate is below 5%.</p>
</section>
</section>
<section id="what-is-the-rate-of-missing-values-per-item" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-rate-of-missing-values-per-item">What is the rate of missing values per item?</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate is.na for each item. Add results to new dataframe</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>missing_per_item <span class="ot">&lt;-</span> <span class="fu">sapply</span>(data, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>missing_per_item_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">missing_count =</span> missing_per_item, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">missing_rate =</span> <span class="fu">round</span>(missing_per_item<span class="sc">/</span> <span class="fu">nrow</span>(data),<span class="dv">2</span>))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(missing_per_item_df, missing_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                         missing_rate
survey_id                        0.00
grade                            0.01
age                              0.21
school                           0.00
race                             0.01
hispanic_latino                  0.03
gender                           0.01
currentSchoolMusic               0.01
currentSchoolMusic_other         0.96
s1_1                             0.01
s1_2                             0.01
s1_3                             0.01
s1_4                             0.01
s1_5                             0.01
s1_6                             0.01
s1_7                             0.01
s1_8                             0.01
s1_9                             0.01
s1_10                            0.02
s1_11                            0.01
s1_12                            0.01
s1_13                            0.01
s2_1                             0.01
s2_2                             0.01
s2_3                             0.01
s2_4                             0.02
s2_5                             0.00
s2_6                             0.01
instrument                       0.00
familyMusic                      0.00
schoolChoir                      0.01
schoolInstrumental               0.00
schoolExtracurricular            0.00
outsideChoir                     0.00
outsideInstrumental              0.01
privateLesson                    0.01
selfTaught                       0.01
s3_1                             0.02
s3_2                             0.01
s3_3                             0.01
s3_4                             0.01
s3_5                             0.03
s3_6                             0.02
s3_7                             0.01
s3_8                             0.02
s3_9                             0.01
s3_10                            0.01
s3_11                            0.02
s3_12                            0.02
s3_13                            0.02
s3_14                            0.02
s3_15                            0.02
s3_16                            0.02
s3_17                            0.02
s3_18                            0.02
s3_19                            0.01
s3_20                            0.02
s3_21                            0.01
s3_22                            0.02
s3_23                            0.02
s3_24                            0.02
s3_25                            0.03
s3_26                            0.02
s3_27                            0.03
s3_28                            0.02</code></pre>
</div>
</div>
<p>Most relevant items (e.g., mindets, msc, and other psychometric measures) had low rate of missing values (&lt;- 4%). Excluding items was not necessary. Because “age” had a high number of missing values (21.00%), I will not include that variable in the data analysis (except for descriptive analysis).</p>
<p>Because currentSchoolMusic_other column only applies to students who selected taking “another music class” besides band, choir, or orchestra, most participants did not fill that blank and, thus, most NA are not missing data. Moreover, “age” had a high rate of missing values. To facilitate imputation, I will only use variables with missing values rate below 5%. Therefore, I removed “age” and “currentSchoolMusic_other from the dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>age, <span class="sc">-</span>currentSchoolMusic_other)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="how-many-observations-do-not-contain-missing-values-and-how-many-do-after-removing-careless-responses" class="level3">
<h3 class="anchored" data-anchor-id="how-many-observations-do-not-contain-missing-values-and-how-many-do-after-removing-careless-responses">How many observations do not contain missing values and how many do (after removing careless responses)?</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(data))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(complete_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 395</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>incomplete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(data))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(incomplete_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 133</code></pre>
</div>
</div>
<p>After removing observation with potential careless responding, 395 observation did not contain missing values in any variable.</p>
<p>Although data are missing in 25.19% of observations, there are some outliers with rates of missing data much higher than most, as seen in the chart below:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate is.na for each observatoin. Add results to new dataframe.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>missing_per_obs_df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), as.character)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    survey_id,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_count =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="fu">c_across</span>(<span class="fu">everything</span>()))),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_rate =</span> <span class="fu">round</span>(missing_count <span class="sc">/</span> <span class="fu">ncol</span>(data), <span class="dv">2</span>),)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co">#View scatterplot to visually identify outliers</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(missing_per_obs_df<span class="sc">$</span>missing_rate, <span class="at">main =</span> <span class="st">"Scatterplot of Rate of with Missing Values per Observation"</span>, <span class="at">xlab =</span> <span class="st">"Observations"</span>, <span class="at">ylab =</span> <span class="st">"missing values rate"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cleaning_3_missing_values_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="flag-observations-with-high-rate-of-missing-values." class="level4">
<h4 class="anchored" data-anchor-id="flag-observations-with-high-rate-of-missing-values.">Flag observations with high rate of missing values.</h4>
<p>To address those outliers, I flagged observations in which missing data accounted for more than 40% of the responses.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create dataframe with observations containing 10%+ of missing values</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>missing_per_obs_high <span class="ot">&lt;-</span> missing_per_obs_df <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(missing_rate <span class="sc">&gt;</span> .<span class="dv">4</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Save flagged observations to vector</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>flagged_obs <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(missing_per_obs_high<span class="sc">$</span>survey_id)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(flagged_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 482</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>flagged_obs_df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(survey_id <span class="sc">%in%</span> flagged_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>During this step, only observations 1 were flagged.</p>
</section>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
</section>
</section>
<section id="removing-or-imputing-observations" class="level2">
<h2 class="anchored" data-anchor-id="removing-or-imputing-observations">Removing or Imputing Observations</h2>
<section id="remove-surveys-with-high-rate-of-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="remove-surveys-with-high-rate-of-missing-values">Remove surveys with high rate of missing values</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(flagged_obs)) <span class="co"># number of observations removed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>survey_id <span class="sc">%in%</span> flagged_obs) <span class="co">#keep only observations not flagged due to high rate of missing data</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data) <span class="co">#New dimension of dataset after flagged observations removed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 527  63</code></pre>
</div>
</div>
<p>Based on the rate of missing data per observation (above 40%)), I removed 1 observations from the dataset.</p>
</section>
<section id="littles-1988-test-of-missingness" class="level3">
<h3 class="anchored" data-anchor-id="littles-1988-test-of-missingness">Little’s (1988) Test of Missingness</h3>
<p>I calculated Little’s Test of Missing to determine the nature of missing data (i.e., MCAR, MAR, MNAR), thus suggesting whether manipulating missing data (deleting or imputing) in the remainder of the dataset would significantly affect data analysis. The following are Little’s test’s hypotheses:</p>
<p>H0: Data is missing completely at random (MCAR)</p>
<p>H1: Data is missing at random (MAR)</p>
<p>H2: Data is missing not a random (MNAR)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mcar_test <span class="ot">&lt;-</span> <span class="fu">mcar_test</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in norm::prelim.norm(data): NAs introduced by coercion to integer range</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mcar_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic    df p.value missing.patterns
      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;            &lt;int&gt;
1     1831.  5487       1               93</code></pre>
</div>
</div>
<p>Based on the results from Little’s Test of Missingness, we fail to reject the null hypothesis. Hence, missing values are likely missing completely at random (MCAR), and data imputation should not significantly alter the results.</p>
</section>
</section>
<section id="multiple-imputation-by-chained-equations" class="level2">
<h2 class="anchored" data-anchor-id="multiple-imputation-by-chained-equations">Multiple Imputation by Chained Equations</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cleaning_3_missing_values_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    survey_id school instrument s2_5 familyMusic schoolInstrumental
395         1      1          1    1           1                  1
3           1      1          1    1           1                  1
7           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
3           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
3           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
6           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
4           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
4           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
3           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
2           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  1
1           1      1          1    1           1                  0
1           1      1          1    1           0                  1
1           1      1          1    0           1                  1
            0      0          0    1           1                  1
    schoolExtracurricular outsideChoir s1_1 s2_1 schoolChoir
395                     1            1    1    1           1
3                       1            1    1    1           1
7                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
3                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
3                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
6                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
4                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
4                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
3                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
2                       1            1    1    1           0
1                       1            1    1    0           1
1                       1            1    1    0           1
1                       1            1    0    1           1
1                       1            1    0    1           1
1                       1            0    1    1           1
1                       0            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
1                       1            1    1    1           1
                        1            1    2    2           2
    outsideInstrumental s3_3 grade race s1_8 s1_11 s2_3 privateLesson
395                   1    1     1    1    1     1    1             1
3                     1    1     1    1    1     1    1             1
7                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
3                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
3                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
6                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
4                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
4                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
3                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             0
1                     1    1     1    1    1     1    0             1
1                     1    1     1    1    1     1    0             1
1                     1    1     1    1    1     1    0             1
1                     1    1     1    1    1     0    1             1
1                     1    1     1    1    1     0    1             1
1                     1    1     1    1    0     1    1             1
1                     1    1     1    1    0     1    1             1
1                     1    1     1    0    1     1    1             1
1                     1    1     1    0    1     1    1             1
2                     1    1     0    1    1     1    1             1
1                     0    0     1    1    1     1    1             0
1                     0    0     1    1    1     1    1             0
2                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    0    0     0    1             1
1                     1    1     0    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
1                     1    1     1    1    1     1    1             1
                      2    2     3    3    3     3    3             3
    selfTaught s1_3 s1_7 s1_9 s2_6 gender s1_2 s1_4 s1_12 s1_13 s2_2 s3_2 s3_4
395          1    1    1    1    1      1    1    1     1     1    1    1    1
3            1    1    1    1    1      1    1    1     1     1    1    1    1
7            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
3            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
3            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
6            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
4            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    0
1            1    1    1    1    1      1    1    1     1     1    1    0    1
1            1    1    1    1    1      1    1    1     1     1    1    0    1
4            1    1    1    1    1      1    1    1     1     1    0    1    1
1            1    1    1    1    1      1    1    1     1     1    0    1    1
1            1    1    1    1    1      1    1    1     1     0    1    1    1
1            1    1    1    1    1      1    1    1     1     0    1    1    1
3            1    1    1    1    1      1    1    1     0     1    1    1    1
1            1    1    1    1    1      1    1    1     0     1    1    1    1
1            1    1    1    1    1      1    1    0     1     1    1    1    1
1            1    1    1    1    1      1    1    0     1     1    1    1    1
1            1    1    1    1    1      1    0    1     1     1    1    1    1
1            1    1    1    1    1      0    1    1     1     1    1    1    1
1            1    1    1    1    1      0    1    1     1     1    1    1    1
2            1    1    1    1    0      1    1    1     1     1    1    1    1
1            1    1    1    1    0      1    1    1     1     0    1    1    1
1            1    1    1    0    1      1    0    1     1     1    1    1    1
2            1    1    0    1    1      1    1    1     1     1    1    1    1
1            1    1    0    1    1      1    1    0     1     1    1    1    1
1            1    0    1    1    1      1    1    1     1     1    1    1    1
1            1    0    1    1    1      1    0    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      0    1    1     1     1    1    1    1
1            1    1    1    1    0      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    0    1    1    1      1    1    1     1     1    1    0    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      0    1    1     1     1    1    1    1
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            0    1    1    1    1      1    1    1     1     1    1    0    0
1            0    1    1    1    1      1    1    0     1     1    1    0    0
2            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    0    1      1    1    1     1     1    1    1    1
1            1    1    1    0    1      1    1    1     1     1    1    1    1
1            1    0    0    0    1      0    0    0     0     0    1    1    0
1            1    1    1    1    1      1    0    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     0    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            0    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
1            1    1    1    1    1      1    1    1     1     1    1    1    1
             3    4    4    4    4      5    5    5     5     5    5    5    5
    s3_10 s1_5 s1_6 s3_7 s3_9 s3_19 s3_21 currentSchoolMusic s2_4 s3_1 s3_8
395     1    1    1    1    1     1     1                  1    1    1    1
3       1    1    1    1    1     1     1                  1    1    1    1
7       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
3       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
3       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
6       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    0    1
1       1    1    1    1    1     1     1                  1    1    0    1
2       1    1    1    1    1     1     1                  1    0    1    1
1       1    1    1    1    1     1     1                  1    0    1    1
4       1    1    1    1    1     1     1                  0    1    1    1
1       1    1    1    1    1     1     1                  0    0    1    1
1       1    1    1    1    1     1     0                  1    1    1    1
1       1    1    1    1    1     0     1                  1    1    1    1
2       1    1    1    1    1     0     0                  1    1    1    1
1       1    1    1    1    0     1     1                  1    1    1    1
1       1    1    1    1    0     1     1                  1    1    1    1
1       1    1    1    0    1     1     1                  1    1    1    1
1       1    1    1    0    1     1     1                  1    1    1    0
1       1    1    0    1    1     1     1                  1    1    1    1
2       1    0    1    1    1     1     1                  1    1    1    1
1       1    0    1    1    1     1     1                  1    1    1    1
1       1    0    0    1    1     1     1                  1    1    1    1
1       1    0    0    1    1     1     1                  1    1    1    1
1       0    1    1    1    1     0     0                  1    1    1    0
1       0    1    1    1    0     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       0    1    1    1    1     1     1                  1    1    1    1
4       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
3       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    0    1    1     1     1                  0    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     0     0                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    0    1
1       1    1    0    1    1     1     1                  1    1    1    1
1       1    1    1    0    1     1     1                  1    0    0    0
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    0     0     0                  1    1    1    0
2       1    1    1    1    1     1     1                  1    1    1    1
1       0    1    1    0    0     1     1                  1    1    0    0
1       0    1    1    0    0     1     1                  1    1    0    0
2       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    0    1    1
1       1    0    0    1    1     1     1                  0    1    1    1
1       1    1    1    0    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    0
1       1    1    1    1    1     1     1                  1    0    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
1       1    1    1    1    1     1     1                  1    1    1    1
        5    6    6    6    6     6     6                  7    7    7    7
    s3_13 s3_18 s1_10 s3_6 s3_11 s3_12 s3_14 s3_15 s3_20 s3_23 s3_24 s3_26
395     1     1     1    1     1     1     1     1     1     1     1     1
3       1     1     1    1     1     1     1     1     1     1     1     1
7       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
3       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     0
1       1     1     1    1     1     1     1     1     1     1     0     1
1       1     1     1    1     1     1     1     1     1     1     0     1
1       1     1     1    1     1     1     1     1     1     0     1     1
1       1     1     1    1     1     1     1     1     1     0     1     1
3       1     1     1    1     1     1     1     1     0     1     1     1
1       1     1     1    1     1     1     1     1     0     1     1     1
2       1     1     1    1     1     1     1     0     1     1     1     1
1       1     1     1    1     1     1     0     1     1     1     1     1
1       1     1     1    1     1     1     0     1     1     1     1     1
1       1     1     1    1     1     0     1     1     1     1     1     1
2       1     1     1    1     0     1     1     1     1     1     1     1
1       1     1     1    1     0     0     1     1     1     1     1     1
1       1     1     1    0     1     1     1     1     1     1     1     1
2       1     1     1    0     1     1     1     1     1     1     1     1
1       1     1     1    0     1     1     1     1     1     1     1     1
1       1     1     1    0     1     1     1     1     1     0     1     1
6       1     1     0    1     1     1     1     1     1     1     1     1
1       1     0     1    1     1     1     1     1     1     1     1     1
1       0     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
4       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     0     0     0     0
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     0     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       0     0     1    1     0     0     0     0     0     0     0     0
1       0     0     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
4       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     0     0
1       1     1     1    1     1     1     1     1     1     1     1     1
1       0     1     1    1     1     1     1     1     1     1     1     1
3       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     0    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     0     1     1     1     1     0
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       0     0     1    1     1     0     0     0     0     0     0     0
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     0     1     1     0     1     0     0     0
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    0     0     0     0     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     0     1    1     1     0     1     0     0     0     0     0
2       1     1     1    1     1     1     1     1     1     1     1     1
1       0     0     1    0     0     0     0     0     1     1     1     1
1       0     0     1    0     0     0     0     0     1     1     1     1
2       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     0    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
1       1     1     1    1     1     1     1     1     1     1     1     1
        7     7     8    8     8     8     8     9     9     9     9     9
    s3_28 s3_17 s3_22 s3_16 s3_27 s3_25 hispanic_latino s3_5    
395     1     1     1     1     1     1               1    1   0
3       1     1     1     1     1     1               1    0   1
7       1     1     1     1     1     1               0    1   1
2       1     1     1     1     1     0               1    1   1
1       1     1     1     1     0     1               1    1   1
3       1     1     1     0     1     1               1    1   1
2       1     1     0     1     1     1               1    1   1
1       1     0     1     1     1     1               1    1   1
1       1     0     1     0     1     1               1    1   2
1       0     1     1     1     0     1               1    1   2
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     0               1    1   2
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               0    1   2
3       1     1     1     1     1     1               1    1   1
1       1     1     0     1     1     1               1    1   2
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
1       1     1     0     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   1
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     0               0    1   4
1       1     1     1     1     1     1               1    1   1
2       1     1     1     1     0     1               1    1   2
1       1     1     0     0     1     0               1    1   4
1       1     1     1     1     0     0               1    0   5
6       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    0   2
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    0   2
4       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     0               1    0   4
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
2       0     1     0     1     0     0               1    1  10
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               0    1   2
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   2
1       1     1     1     0     1     1               1    1   2
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    0   2
1       1     1     1     1     1     1               1    1   2
1       1     1     0     1     1     1               1    1   3
1       0     0     0     0     0     0               1    1  20
1       1     0     1     1     0     1               0    0   8
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
1       0     0     1     1     1     1               1    0   5
4       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   3
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   2
3       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   3
1       1     1     1     1     1     0               1    0   5
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               0    1   2
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   2
1       0     1     1     1     1     1               1    1   3
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   2
1       0     0     0     0     0     0               1    1  18
1       1     0     1     0     1     1               1    1   3
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   1
1       0     1     1     1     0     0               1    0  11
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     0     1               1    1  12
1       1     1     1     1     1     1               0    1   2
1       0     1     0     1     0     0               0    1  18
2       1     1     1     1     1     1               1    1   1
1       1     0     1     0     1     1               1    0  21
1       1     0     1     0     1     1               1    0  22
2       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   2
1       1     1     1     1     1     1               1    1   3
1       1     1     1     1     1     1               0    0  19
1       1     1     1     1     1     1               1    1   4
1       1     0     1     1     1     1               1    1   4
1       1     1     1     1     1     1               1    1   2
1       1     1     1     0     1     1               1    1   3
1       1     1     1     1     1     1               1    1   1
1       1     1     1     1     1     1               1    1   1
        9    10    11    12    13    14              15   15 359</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>imputed_data <span class="ot">&lt;-</span> <span class="fu">mice</span>(data, <span class="at">m =</span> <span class="dv">5</span>, <span class="at">method =</span> <span class="st">"rf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  1   2  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  1   3  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  1   4  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  1   5  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  2   1  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  2   2  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  2   3  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  2   4  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  2   5  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  3   1  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  3   2  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  3   3  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  3   4  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  3   5  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  4   1  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  4   2  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  4   3  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  4   4  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  4   5  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  5   1  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  5   2  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  5   3  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  5   4  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28
  5   5  grade  s1_1  s1_2  s1_3  s1_4  s1_5  s1_6  s1_7  s1_8  s1_9  s1_10  s1_11  s1_12  s1_13  s2_1  s2_2  s2_3  s2_4  s2_5  s2_6  schoolChoir  schoolInstrumental  schoolExtracurricular  outsideChoir  outsideInstrumental  privateLesson  selfTaught  s3_1  s3_2  s3_3  s3_4  s3_5  s3_6  s3_7  s3_8  s3_9  s3_10  s3_11  s3_12  s3_13  s3_14  s3_15  s3_16  s3_17  s3_18  s3_19  s3_20  s3_21  s3_22  s3_23  s3_24  s3_25  s3_26  s3_27  s3_28</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Number of logged events: 7</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(imputed_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mids
Number of multiple imputations:  5 
Imputation methods:
            survey_id                 grade                school 
                   ""                  "rf"                    "" 
                 race       hispanic_latino                gender 
                   ""                    ""                    "" 
   currentSchoolMusic                  s1_1                  s1_2 
                   ""                  "rf"                  "rf" 
                 s1_3                  s1_4                  s1_5 
                 "rf"                  "rf"                  "rf" 
                 s1_6                  s1_7                  s1_8 
                 "rf"                  "rf"                  "rf" 
                 s1_9                 s1_10                 s1_11 
                 "rf"                  "rf"                  "rf" 
                s1_12                 s1_13                  s2_1 
                 "rf"                  "rf"                  "rf" 
                 s2_2                  s2_3                  s2_4 
                 "rf"                  "rf"                  "rf" 
                 s2_5                  s2_6            instrument 
                 "rf"                  "rf"                    "" 
          familyMusic           schoolChoir    schoolInstrumental 
                   ""                  "rf"                  "rf" 
schoolExtracurricular          outsideChoir   outsideInstrumental 
                 "rf"                  "rf"                  "rf" 
        privateLesson            selfTaught                  s3_1 
                 "rf"                  "rf"                  "rf" 
                 s3_2                  s3_3                  s3_4 
                 "rf"                  "rf"                  "rf" 
                 s3_5                  s3_6                  s3_7 
                 "rf"                  "rf"                  "rf" 
                 s3_8                  s3_9                 s3_10 
                 "rf"                  "rf"                  "rf" 
                s3_11                 s3_12                 s3_13 
                 "rf"                  "rf"                  "rf" 
                s3_14                 s3_15                 s3_16 
                 "rf"                  "rf"                  "rf" 
                s3_17                 s3_18                 s3_19 
                 "rf"                  "rf"                  "rf" 
                s3_20                 s3_21                 s3_22 
                 "rf"                  "rf"                  "rf" 
                s3_23                 s3_24                 s3_25 
                 "rf"                  "rf"                  "rf" 
                s3_26                 s3_27                 s3_28 
                 "rf"                  "rf"                  "rf" 
PredictorMatrix:
                survey_id grade school race hispanic_latino gender
survey_id               0     1      0    0               0      0
grade                   1     0      0    0               0      0
school                  1     1      0    0               0      0
race                    0     0      0    0               0      0
hispanic_latino         0     0      0    0               0      0
gender                  0     0      0    0               0      0
                currentSchoolMusic s1_1 s1_2 s1_3 s1_4 s1_5 s1_6 s1_7 s1_8 s1_9
survey_id                        0    1    1    1    1    1    1    1    1    1
grade                            0    1    1    1    1    1    1    1    1    1
school                           0    1    1    1    1    1    1    1    1    1
race                             0    0    0    0    0    0    0    0    0    0
hispanic_latino                  0    0    0    0    0    0    0    0    0    0
gender                           0    0    0    0    0    0    0    0    0    0
                s1_10 s1_11 s1_12 s1_13 s2_1 s2_2 s2_3 s2_4 s2_5 s2_6
survey_id           1     1     1     1    1    1    1    1    1    1
grade               1     1     1     1    1    1    1    1    1    1
school              1     1     1     1    1    1    1    1    1    1
race                0     0     0     0    0    0    0    0    0    0
hispanic_latino     0     0     0     0    0    0    0    0    0    0
gender              0     0     0     0    0    0    0    0    0    0
                instrument familyMusic schoolChoir schoolInstrumental
survey_id                0           0           1                  1
grade                    0           0           1                  1
school                   0           0           1                  1
race                     0           0           0                  0
hispanic_latino          0           0           0                  0
gender                   0           0           0                  0
                schoolExtracurricular outsideChoir outsideInstrumental
survey_id                           1            1                   1
grade                               1            1                   1
school                              1            1                   1
race                                0            0                   0
hispanic_latino                     0            0                   0
gender                              0            0                   0
                privateLesson selfTaught s3_1 s3_2 s3_3 s3_4 s3_5 s3_6 s3_7
survey_id                   1          1    1    1    1    1    1    1    1
grade                       1          1    1    1    1    1    1    1    1
school                      1          1    1    1    1    1    1    1    1
race                        0          0    0    0    0    0    0    0    0
hispanic_latino             0          0    0    0    0    0    0    0    0
gender                      0          0    0    0    0    0    0    0    0
                s3_8 s3_9 s3_10 s3_11 s3_12 s3_13 s3_14 s3_15 s3_16 s3_17 s3_18
survey_id          1    1     1     1     1     1     1     1     1     1     1
grade              1    1     1     1     1     1     1     1     1     1     1
school             1    1     1     1     1     1     1     1     1     1     1
race               0    0     0     0     0     0     0     0     0     0     0
hispanic_latino    0    0     0     0     0     0     0     0     0     0     0
gender             0    0     0     0     0     0     0     0     0     0     0
                s3_19 s3_20 s3_21 s3_22 s3_23 s3_24 s3_25 s3_26 s3_27 s3_28
survey_id           1     1     1     1     1     1     1     1     1     1
grade               1     1     1     1     1     1     1     1     1     1
school              1     1     1     1     1     1     1     1     1     1
race                0     0     0     0     0     0     0     0     0     0
hispanic_latino     0     0     0     0     0     0     0     0     0     0
gender              0     0     0     0     0     0     0     0     0     0
Number of logged events:  7 
  it im dep     meth                out
1  0  0     constant             school
2  0  0     constant               race
3  0  0     constant    hispanic_latino
4  0  0     constant             gender
5  0  0     constant currentSchoolMusic
6  0  0     constant         instrument</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>imputed_dataset <span class="ot">&lt;-</span> <span class="fu">complete</span>(imputed_data)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Update number of complete and incomplete cases</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(imputed_dataset))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(complete_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 503</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>incomplete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(imputed_dataset))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(incomplete_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>imputed_dataset <span class="ot">&lt;-</span> imputed_dataset <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(<span class="fu">complete.cases</span>(imputed_dataset))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>After imputing data using the “mice” function the number of complete cases increased to 503, and 24 observations still contained missing data. Hence, I removed those observations from the data set.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(imputed_dataset, <span class="st">"data/middle_school_music_mindsets_clean_3_imputed.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb43" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Missing Values"</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> Diego Pinto</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="an">code-fold:</span><span class="co"> true</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="an">theme:</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co">  light: cosmo</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="an">editor_options:</span><span class="co"> </span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="co">  chunk_output_type: inline</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="fu"># Dealing with missing values</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"~/Desktop/R_projects/msc"</span>)</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># Clear Global Environment</span></span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mice"</span>) <span class="co">#for multiple imputation</span></span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/middle_school_music_mindsets_clean_2_careless_removed.csv"</span>)</span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analyzing missing values</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a><span class="fu">### What is the ratio of missing values in the entire dataset?</span></span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-41"><a href="#cb43-41" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-42"><a href="#cb43-42" aria-hidden="true" tabindex="-1"></a>missing_sum <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(data)) <span class="co">#sum of all missing values</span></span>
<span id="cb43-43"><a href="#cb43-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-44"><a href="#cb43-44" aria-hidden="true" tabindex="-1"></a>data_points_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data) <span class="sc">*</span> <span class="fu">ncol</span>(data) <span class="co">#number of datapoints in the datafrae</span></span>
<span id="cb43-45"><a href="#cb43-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-46"><a href="#cb43-46" aria-hidden="true" tabindex="-1"></a>missing_percentage <span class="ot">&lt;-</span> missing_sum <span class="sc">/</span>data_points_count <span class="co">#percentage of all missing values</span></span>
<span id="cb43-47"><a href="#cb43-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-48"><a href="#cb43-48" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_percentage)</span>
<span id="cb43-49"><a href="#cb43-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-50"><a href="#cb43-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-51"><a href="#cb43-51" aria-hidden="true" tabindex="-1"></a>The dataset contained <span class="in">`r missing_sum`</span> missing data points, which corresponds to <span class="in">`r sprintf("%.2f%%", missing_percentage * 100)`</span> of the entire data set.</span>
<span id="cb43-52"><a href="#cb43-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-53"><a href="#cb43-53" aria-hidden="true" tabindex="-1"></a><span class="fu">### What section of the survey contains the most missing values?</span></span>
<span id="cb43-54"><a href="#cb43-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-55"><a href="#cb43-55" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Save section of survey into separate dataframes for following calculations:</span></span>
<span id="cb43-56"><a href="#cb43-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-59"><a href="#cb43-59" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-60"><a href="#cb43-60" aria-hidden="true" tabindex="-1"></a>data_demographic <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-61"><a href="#cb43-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(survey_id<span class="sc">:</span>currentSchoolMusic) <span class="co">#demographic variables, except currentSchoolMusic_other</span></span>
<span id="cb43-62"><a href="#cb43-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-63"><a href="#cb43-63" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-64"><a href="#cb43-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"s1"</span>)) <span class="co">#section 1 (Likert 1-4)</span></span>
<span id="cb43-65"><a href="#cb43-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-66"><a href="#cb43-66" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-67"><a href="#cb43-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"s2"</span>)) <span class="co">#section 2 (Likert 1-7, mostly)</span></span>
<span id="cb43-68"><a href="#cb43-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-69"><a href="#cb43-69" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-70"><a href="#cb43-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"s3"</span>)) <span class="co">#section 3 (Likert 1-4)</span></span>
<span id="cb43-71"><a href="#cb43-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-72"><a href="#cb43-72" aria-hidden="true" tabindex="-1"></a>measures_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb43-73"><a href="#cb43-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(s1_1<span class="sc">:</span>s3_28) <span class="sc">%&gt;%</span></span>
<span id="cb43-74"><a href="#cb43-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="co">#sections 1, 2, and 3 combined, excluding variables with character data (i.e., instrument_play_best).</span></span>
<span id="cb43-75"><a href="#cb43-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-76"><a href="#cb43-76" aria-hidden="true" tabindex="-1"></a><span class="co">#data_family_subset &lt;- filter(data, is.na(data$s2_8))</span></span>
<span id="cb43-77"><a href="#cb43-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-78"><a href="#cb43-78" aria-hidden="true" tabindex="-1"></a><span class="co">#survey_id &lt;- data$survey_id</span></span>
<span id="cb43-79"><a href="#cb43-79" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-80"><a href="#cb43-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-81"><a href="#cb43-81" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Calculate missing values per survey section</span></span>
<span id="cb43-82"><a href="#cb43-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-85"><a href="#cb43-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-86"><a href="#cb43-86" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in demographic questions</span></span>
<span id="cb43-87"><a href="#cb43-87" aria-hidden="true" tabindex="-1"></a>demographics_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(data_demographic))) <span class="sc">/</span> (<span class="fu">nrow</span>(data_demographic) <span class="sc">*</span> <span class="fu">ncol</span>(data_demographic))</span>
<span id="cb43-88"><a href="#cb43-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-89"><a href="#cb43-89" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in sections 1</span></span>
<span id="cb43-90"><a href="#cb43-90" aria-hidden="true" tabindex="-1"></a>s1_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(s1))) <span class="sc">/</span> (<span class="fu">nrow</span>(s1) <span class="sc">*</span> <span class="fu">ncol</span>(s1))</span>
<span id="cb43-91"><a href="#cb43-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-92"><a href="#cb43-92" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in section 2 (s21_:s2)</span></span>
<span id="cb43-93"><a href="#cb43-93" aria-hidden="true" tabindex="-1"></a>s2_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(s2))) <span class="sc">/</span> (<span class="fu">nrow</span>(s2) <span class="sc">*</span> <span class="fu">ncol</span>(s2))</span>
<span id="cb43-94"><a href="#cb43-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-95"><a href="#cb43-95" aria-hidden="true" tabindex="-1"></a><span class="co">#missing values in sections 3</span></span>
<span id="cb43-96"><a href="#cb43-96" aria-hidden="true" tabindex="-1"></a>s3_missing_rate <span class="ot">&lt;-</span> (<span class="fu">sum</span>(<span class="fu">is.na.data.frame</span>(s3))) <span class="sc">/</span> (<span class="fu">nrow</span>(s3) <span class="sc">*</span> <span class="fu">ncol</span>(s3))</span>
<span id="cb43-97"><a href="#cb43-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-98"><a href="#cb43-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-99"><a href="#cb43-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-100"><a href="#cb43-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-101"><a href="#cb43-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-102"><a href="#cb43-102" aria-hidden="true" tabindex="-1"></a>The rate of missing data per survey section was as follow:</span>
<span id="cb43-103"><a href="#cb43-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-104"><a href="#cb43-104" aria-hidden="true" tabindex="-1"></a>• Demographics: <span class="in">`r sprintf("%.2f%%", demographics_missing_rate * 100)`</span></span>
<span id="cb43-105"><a href="#cb43-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-106"><a href="#cb43-106" aria-hidden="true" tabindex="-1"></a>• Section 1: <span class="in">`r sprintf("%.2f%%", s1_missing_rate * 100)`</span></span>
<span id="cb43-107"><a href="#cb43-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-108"><a href="#cb43-108" aria-hidden="true" tabindex="-1"></a>• Section 2: <span class="in">`r sprintf("%.2f%%", s2_missing_rate * 100)`</span></span>
<span id="cb43-109"><a href="#cb43-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-110"><a href="#cb43-110" aria-hidden="true" tabindex="-1"></a>• Section 3: <span class="in">`r sprintf("%.2f%%", s3_missing_rate * 100)`</span></span>
<span id="cb43-111"><a href="#cb43-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-112"><a href="#cb43-112" aria-hidden="true" tabindex="-1"></a>The demographic section has highest rate of missing values. Still, that rate is below 5%.</span>
<span id="cb43-113"><a href="#cb43-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-114"><a href="#cb43-114" aria-hidden="true" tabindex="-1"></a><span class="fu">### What is the rate of missing values per item?</span></span>
<span id="cb43-115"><a href="#cb43-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-118"><a href="#cb43-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-119"><a href="#cb43-119" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate is.na for each item. Add results to new dataframe</span></span>
<span id="cb43-120"><a href="#cb43-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-121"><a href="#cb43-121" aria-hidden="true" tabindex="-1"></a>missing_per_item <span class="ot">&lt;-</span> <span class="fu">sapply</span>(data, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb43-122"><a href="#cb43-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-123"><a href="#cb43-123" aria-hidden="true" tabindex="-1"></a>missing_per_item_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">missing_count =</span> missing_per_item, </span>
<span id="cb43-124"><a href="#cb43-124" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">missing_rate =</span> <span class="fu">round</span>(missing_per_item<span class="sc">/</span> <span class="fu">nrow</span>(data),<span class="dv">2</span>))</span>
<span id="cb43-125"><a href="#cb43-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-126"><a href="#cb43-126" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(missing_per_item_df, missing_rate)</span>
<span id="cb43-127"><a href="#cb43-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-128"><a href="#cb43-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-129"><a href="#cb43-129" aria-hidden="true" tabindex="-1"></a>Most relevant items (e.g., mindets, msc, and other psychometric measures) had low rate of missing values (<span class="sc">\&lt;</span>- 4%). Excluding items was not necessary. Because "age" had a high number of missing values (<span class="in">`r sprintf("%.2f%%", missing_per_item_df["age", "missing_rate"] * 100)`</span>), I will not include that variable in the data analysis (except for descriptive analysis).</span>
<span id="cb43-130"><a href="#cb43-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-131"><a href="#cb43-131" aria-hidden="true" tabindex="-1"></a>Because currentSchoolMusic_other column only applies to students who selected taking "another music class" besides band, choir, or orchestra, most participants did not fill that blank and, thus, most NA are not missing data. Moreover, "age" had a high rate of missing values. To facilitate imputation, I will only use variables with missing values rate below 5%. Therefore, I removed "age" and "currentSchoolMusic_other from the dataset.</span>
<span id="cb43-132"><a href="#cb43-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-135"><a href="#cb43-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-136"><a href="#cb43-136" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-137"><a href="#cb43-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>age, <span class="sc">-</span>currentSchoolMusic_other)</span>
<span id="cb43-138"><a href="#cb43-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-139"><a href="#cb43-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-140"><a href="#cb43-140" aria-hidden="true" tabindex="-1"></a><span class="fu">### How many observations do not contain missing values and how many do (after removing careless responses)?</span></span>
<span id="cb43-141"><a href="#cb43-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-144"><a href="#cb43-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-145"><a href="#cb43-145" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(data))</span>
<span id="cb43-146"><a href="#cb43-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-147"><a href="#cb43-147" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(complete_cases)</span>
<span id="cb43-148"><a href="#cb43-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-149"><a href="#cb43-149" aria-hidden="true" tabindex="-1"></a>incomplete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(data))</span>
<span id="cb43-150"><a href="#cb43-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-151"><a href="#cb43-151" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(incomplete_cases)</span>
<span id="cb43-152"><a href="#cb43-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-153"><a href="#cb43-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-154"><a href="#cb43-154" aria-hidden="true" tabindex="-1"></a>After removing observation with potential careless responding, <span class="in">`r complete_cases`</span> observation did not contain missing values in any variable.</span>
<span id="cb43-155"><a href="#cb43-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-156"><a href="#cb43-156" aria-hidden="true" tabindex="-1"></a>Although data are missing in <span class="in">`r sprintf("%.2f%%", incomplete_cases/nrow(data) * 100)`</span> of observations, there are some outliers with rates of missing data much higher than most, as seen in the chart below:</span>
<span id="cb43-157"><a href="#cb43-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-160"><a href="#cb43-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-161"><a href="#cb43-161" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate is.na for each observatoin. Add results to new dataframe.</span></span>
<span id="cb43-162"><a href="#cb43-162" aria-hidden="true" tabindex="-1"></a>missing_per_obs_df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-163"><a href="#cb43-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), as.character)) <span class="sc">%&gt;%</span> </span>
<span id="cb43-164"><a href="#cb43-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb43-165"><a href="#cb43-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb43-166"><a href="#cb43-166" aria-hidden="true" tabindex="-1"></a>    survey_id,</span>
<span id="cb43-167"><a href="#cb43-167" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_count =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="fu">c_across</span>(<span class="fu">everything</span>()))),</span>
<span id="cb43-168"><a href="#cb43-168" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_rate =</span> <span class="fu">round</span>(missing_count <span class="sc">/</span> <span class="fu">ncol</span>(data), <span class="dv">2</span>),)</span>
<span id="cb43-169"><a href="#cb43-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-170"><a href="#cb43-170" aria-hidden="true" tabindex="-1"></a><span class="co">#View scatterplot to visually identify outliers</span></span>
<span id="cb43-171"><a href="#cb43-171" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(missing_per_obs_df<span class="sc">$</span>missing_rate, <span class="at">main =</span> <span class="st">"Scatterplot of Rate of with Missing Values per Observation"</span>, <span class="at">xlab =</span> <span class="st">"Observations"</span>, <span class="at">ylab =</span> <span class="st">"missing values rate"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) </span>
<span id="cb43-172"><a href="#cb43-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-173"><a href="#cb43-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-174"><a href="#cb43-174" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Flag observations with high rate of missing values.</span></span>
<span id="cb43-175"><a href="#cb43-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-176"><a href="#cb43-176" aria-hidden="true" tabindex="-1"></a>To address those outliers, I flagged observations in which missing data accounted for more than 40% of the responses.</span>
<span id="cb43-177"><a href="#cb43-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-180"><a href="#cb43-180" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-181"><a href="#cb43-181" aria-hidden="true" tabindex="-1"></a><span class="co">#Create dataframe with observations containing 10%+ of missing values</span></span>
<span id="cb43-182"><a href="#cb43-182" aria-hidden="true" tabindex="-1"></a>missing_per_obs_high <span class="ot">&lt;-</span> missing_per_obs_df <span class="sc">%&gt;%</span> </span>
<span id="cb43-183"><a href="#cb43-183" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(missing_rate <span class="sc">&gt;</span> .<span class="dv">4</span>)</span>
<span id="cb43-184"><a href="#cb43-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-185"><a href="#cb43-185" aria-hidden="true" tabindex="-1"></a><span class="co">#Save flagged observations to vector</span></span>
<span id="cb43-186"><a href="#cb43-186" aria-hidden="true" tabindex="-1"></a>flagged_obs <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(missing_per_obs_high<span class="sc">$</span>survey_id)</span>
<span id="cb43-187"><a href="#cb43-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-188"><a href="#cb43-188" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(flagged_obs)</span>
<span id="cb43-189"><a href="#cb43-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-190"><a href="#cb43-190" aria-hidden="true" tabindex="-1"></a>flagged_obs_df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-191"><a href="#cb43-191" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(survey_id <span class="sc">%in%</span> flagged_obs)</span>
<span id="cb43-192"><a href="#cb43-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-193"><a href="#cb43-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-194"><a href="#cb43-194" aria-hidden="true" tabindex="-1"></a>During this step, only observations <span class="in">`r nrow(flagged_obs_df)`</span> were flagged.</span>
<span id="cb43-195"><a href="#cb43-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-196"><a href="#cb43-196" aria-hidden="true" tabindex="-1"></a><span class="fu">### </span></span>
<span id="cb43-197"><a href="#cb43-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-198"><a href="#cb43-198" aria-hidden="true" tabindex="-1"></a><span class="fu">## Removing or Imputing Observations</span></span>
<span id="cb43-199"><a href="#cb43-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-200"><a href="#cb43-200" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Remove surveys with high rate of missing values</span></span>
<span id="cb43-201"><a href="#cb43-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-204"><a href="#cb43-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-205"><a href="#cb43-205" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(flagged_obs)) <span class="co"># number of observations removed</span></span>
<span id="cb43-206"><a href="#cb43-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-207"><a href="#cb43-207" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb43-208"><a href="#cb43-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>survey_id <span class="sc">%in%</span> flagged_obs) <span class="co">#keep only observations not flagged due to high rate of missing data</span></span>
<span id="cb43-209"><a href="#cb43-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-210"><a href="#cb43-210" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data) <span class="co">#New dimension of dataset after flagged observations removed</span></span>
<span id="cb43-211"><a href="#cb43-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-212"><a href="#cb43-212" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-213"><a href="#cb43-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-214"><a href="#cb43-214" aria-hidden="true" tabindex="-1"></a>Based on the rate of missing data per observation (above 40%)), I removed <span class="in">`r sum(!is.na(flagged_obs))`</span> observations from the dataset.</span>
<span id="cb43-215"><a href="#cb43-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-216"><a href="#cb43-216" aria-hidden="true" tabindex="-1"></a><span class="fu">### Little's (1988) Test of Missingness</span></span>
<span id="cb43-217"><a href="#cb43-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-218"><a href="#cb43-218" aria-hidden="true" tabindex="-1"></a>I calculated Little's Test of Missing to determine the nature of missing data (i.e., MCAR, MAR, MNAR), thus suggesting whether manipulating missing data (deleting or imputing) in the remainder of the dataset would significantly affect data analysis. The following are Little's test's hypotheses:</span>
<span id="cb43-219"><a href="#cb43-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-220"><a href="#cb43-220" aria-hidden="true" tabindex="-1"></a>H0: Data is missing completely at random (MCAR)</span>
<span id="cb43-221"><a href="#cb43-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-222"><a href="#cb43-222" aria-hidden="true" tabindex="-1"></a>H1: Data is missing at random (MAR)</span>
<span id="cb43-223"><a href="#cb43-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-224"><a href="#cb43-224" aria-hidden="true" tabindex="-1"></a>H2: Data is missing not a random (MNAR)</span>
<span id="cb43-225"><a href="#cb43-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-228"><a href="#cb43-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-229"><a href="#cb43-229" aria-hidden="true" tabindex="-1"></a>mcar_test <span class="ot">&lt;-</span> <span class="fu">mcar_test</span>(data)</span>
<span id="cb43-230"><a href="#cb43-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-231"><a href="#cb43-231" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mcar_test)</span>
<span id="cb43-232"><a href="#cb43-232" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-233"><a href="#cb43-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-234"><a href="#cb43-234" aria-hidden="true" tabindex="-1"></a>Based on the results from Little's Test of Missingness, we fail to reject the null hypothesis. Hence, missing values are likely missing completely at random (MCAR), and data imputation should not significantly alter the results.</span>
<span id="cb43-235"><a href="#cb43-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-236"><a href="#cb43-236" aria-hidden="true" tabindex="-1"></a><span class="fu">## Multiple Imputation by Chained Equations</span></span>
<span id="cb43-237"><a href="#cb43-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-240"><a href="#cb43-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-241"><a href="#cb43-241" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(data)</span>
<span id="cb43-242"><a href="#cb43-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-243"><a href="#cb43-243" aria-hidden="true" tabindex="-1"></a>imputed_data <span class="ot">&lt;-</span> <span class="fu">mice</span>(data, <span class="at">m =</span> <span class="dv">5</span>, <span class="at">method =</span> <span class="st">"rf"</span>)</span>
<span id="cb43-244"><a href="#cb43-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-245"><a href="#cb43-245" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(imputed_data)</span>
<span id="cb43-246"><a href="#cb43-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-247"><a href="#cb43-247" aria-hidden="true" tabindex="-1"></a>imputed_dataset <span class="ot">&lt;-</span> <span class="fu">complete</span>(imputed_data)</span>
<span id="cb43-248"><a href="#cb43-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-249"><a href="#cb43-249" aria-hidden="true" tabindex="-1"></a><span class="co">#Update number of complete and incomplete cases</span></span>
<span id="cb43-250"><a href="#cb43-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-251"><a href="#cb43-251" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(imputed_dataset))</span>
<span id="cb43-252"><a href="#cb43-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-253"><a href="#cb43-253" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(complete_cases)</span>
<span id="cb43-254"><a href="#cb43-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-255"><a href="#cb43-255" aria-hidden="true" tabindex="-1"></a>incomplete_cases <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(imputed_dataset))</span>
<span id="cb43-256"><a href="#cb43-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-257"><a href="#cb43-257" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(incomplete_cases)</span>
<span id="cb43-258"><a href="#cb43-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-259"><a href="#cb43-259" aria-hidden="true" tabindex="-1"></a>imputed_dataset <span class="ot">&lt;-</span> imputed_dataset <span class="sc">%&gt;%</span> </span>
<span id="cb43-260"><a href="#cb43-260" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(<span class="fu">complete.cases</span>(imputed_dataset))</span>
<span id="cb43-261"><a href="#cb43-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-262"><a href="#cb43-262" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb43-263"><a href="#cb43-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-264"><a href="#cb43-264" aria-hidden="true" tabindex="-1"></a>After imputing data using the "mice" function the number of complete cases increased to <span class="in">`r complete_cases`</span>, and <span class="in">`r incomplete_cases`</span> observations still contained missing data. Hence, I removed those observations from the data set.</span>
<span id="cb43-265"><a href="#cb43-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-268"><a href="#cb43-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-269"><a href="#cb43-269" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(imputed_dataset, <span class="st">"data/middle_school_music_mindsets_clean_3_imputed.csv"</span>)</span>
<span id="cb43-270"><a href="#cb43-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>